### ISSUE TITLE
stats['Recent damage'] uvek ima vrednost 0

### ISSUE THREAD

**Issue by mirjanic** [mgcsweek/csweekmon#21]
self.stats['Recent damage'] se pojavljuje ukupno 4 puta u kodu: 2 puta u counter.py, jednom u strategies.py i jednom u csweekmon.py. Od ta 4 referenciranja, samo mu se u poslednjem postavlja vrednost i to na 0, što je po mom mišljenju očigledna greška. Issues su zabranjeni na vdm370/csweekmon pa ga otvaram ovde.

**Comment by Dreian** [comment]
Fixed.
