### ISSUE TITLE
Power Potion inconsistent

### ISSUE THREAD

**Issue by rand0musername** [mgcsweek/csweekmon#3]
`power_potion.py` top-level comment states that the increase is in [4, 6] but [random.randint](https://docs.python.org/2/library/random.html#random.randint)(4, 7) returns a value in [4, 7]. This is either a comment error or a bug (due to randint being mega unintuitive) but it should at least be consistent.

**Comment by rand0musername** [comment]
Now that I've seen the rest of the code it seems like all `random.randint` calls should be changed (e.g. `random.randint(0, 100)` should be `random.randint(0, 99)`.

**Comment by Dreian** [comment]
Well spotted!

**Comment by Dreian** [comment]
Fixed.
