### ISSUE TITLE
strategy_gen.py

### ISSUE THREAD

**Issue by rand0musername** [mgcsweek/csweekmon#5]
I am not sure I understand what `strategy_gen.py` should generate strategy classes from? Competitors still have to write the core logic (`choose_action`) in python and there is not much boilerplate around that.

**Comment by Dreian** [comment]
It will provide a UI to allocate stats and choose moves, then create a new file (e.g. `new_strategy.py`) with stubs in core logic. Not too important.

**Comment by rand0musername** [comment]
Ah, ok. I like this, less number juggling :) 

Shouldn't be too hard to implement, I hope someone has time!

**Comment by Dreian** [comment]
Done!
